"""
Half-cheetah environment with target velocity, as described in [1]. The code is adapted from

https://github.com/cbfinn/maml_rl/blob/9c8e2ebd741cb0c7b8bf2d040c4caeeb8e06cc95/rllab/envs/mujoco/half_cheetah_env_rand.py

The half-cheetah follows the dynamics from MuJoCo [2], and receives at each time step a reward composed of a control
cost and a penalty equal to the difference between its current velocity and the target velocity.

The tasks are generated by sampling the target velocities from the uniform distribution on [0, 2].

[1] Chelsea Finn, Pieter Abbeel, Sergey Levine, "Model-Agnostic
    Meta-Learning for Fast Adaptation of Deep Networks", 2017
    (https://arxiv.org/abs/1703.03400)
[2] Emanuel Todorov, Tom Erez, Yuval Tassa, "MuJoCo: A physics engine for
    model-based control", 2012
    (https://homes.cs.washington.edu/~todorov/papers/TodorovIROS12.pdf)
"""

import numpy as np
from src.rl.envs import BaseMetaEnv
from .base_half_cheetah import HalfCheetahEnv as HalfCheetahEnv_
from gym.utils import EzPickle


class HalfCheetahRandVel(BaseMetaEnv, HalfCheetahEnv_, EzPickle):

  def __init__(self, **kwargs):
    """
    Initialize a Half Cheetah environment with randomized reward structure.
    """
    super(HalfCheetahRandVel, self).__init__(kwargs)
    self.set_task(self.sample_tasks(1)[0])

    # @todo figure out what needs to be fixed here.
    EzPickle.__init__(self)
    self._goal_velocity = 0.
    pass

  def sample_tasks(self, num_tasks: int):
    """
    Sample a given number of goal velocities.

    Args:
      num_tasks (int): The number of tasks to sample from the current environment.

    Returns:
      (np.ndarray) an array of sampled values.
    """
    return np.random.uniform(0.0, 3.0, (num_tasks, ))

  def set_task(self, goal_velocity: float) -> None:
    """
    In the case of this environment, setting the

    Args:
      goal_velocity (float): Goal velocity for the Half-Cheetah environment.

    Returns:
      None
    """
    self._goal_velocity = goal_velocity

  def get_task(self):
    """
    In the case of this environment, will return the goal velocity for the half-cheetah.

    Returns:
      (float) the goal velocity.
    """
    return self._goal_velocity

  def step(self, action):
    """
    Given an action, take a step in the environment.

    Args:
      action (ActType): an action provided by the agent

    Returns:
      [ob, reward, done, dict] tuple containing observation, reward, whether an episode is done, and auxiliary
        diagnostic info.
    """
    x_pos_before = self.sim.data.qpos[0]
    self.do_simulation(action, self.frame_skip)
    x_pos_after = self.sim.data.qpos[0]

    ob = self._get_obs()
    reward_ctrl = - 0.5 * 0.1 * np.square(action).sum()
    forward_velocity = (x_pos_after - x_pos_before) / self.dt

    reward_run = - np.abs(forward_velocity - self._goal_velocity)
    reward = reward_ctrl + reward_run
    done = False

    return ob, reward, done, dict(forward_vel = forward_velocity, reward_run = reward_run, reward_ctrl = reward_ctrl)

  def _get_obs(self) -> np.ndarray:
    """
    Returns the observation for the current step.

    Returns:
      (np.ndarray) with the observation.
    """
    return np.concatenate([
      self.sim.data.qpos.flat[1:],
      self.sim.data.qvel.flat
    ])

  def reset_model(self):
    """
    Reset the current model of the environment and return the current observation for the environment.

    Returns:
      (np.ndarray) Current observation for the environment.
    """
    qpos = self.init_qpos + self.np_random.uniform(low = -.1, high = .1, size = self.model.nq)
    qvel = self.init_qvel + self.np_random.randn(self.model.nv) * .1
    self.set_state(qpos, qvel)

    return self._get_obs()

  def __str__(self):
    return 'HalfCheetahRandDirecVel'
