"""
Half-cheetah environment with target direction, as described in [1]. The code is adapted from

https://github.com/cbfinn/maml_rl/blob/9c8e2ebd741cb0c7b8bf2d040c4caeeb8e06cc95/rllab/envs/mujoco/half_cheetah_env_rand_direc.py

The half-cheetah follows the dynamics from MuJoCo [2], and receives at each
time step a reward composed of a control cost and a reward equal to its
velocity in the target direction. The tasks are generated by sampling the
target directions from a Bernoulli distribution on {-1, 1} with parameter
0.5 (-1: backward, +1: forward).

[1] Chelsea Finn, Pieter Abbeel, Sergey Levine, "Model-Agnostic
    Meta-Learning for Fast Adaptation of Deep Networks", 2017
    (https://arxiv.org/abs/1703.03400)

[2] Emanuel Todorov, Tom Erez, Yuval Tassa, "MuJoCo: A physics engine for
    model-based control", 2012
    (https://homes.cs.washington.edu/~todorov/papers/TodorovIROS12.pdf)
"""

import numpy as np
from src.rl.envs import BaseMetaEnv
from .base_half_cheetah import HalfCheetahEnv as HalfCheetahEnv_
from gym.utils import EzPickle


class HalfCheetahRandDirec(BaseMetaEnv, HalfCheetahEnv_, EzPickle):

  def __init__(self, goal_direction: float = None, **kwargs):
    """
    Initialize a Half Cheetah environment with randomized reward structure.
    """
    super(HalfCheetahRandDirec, self).__init__(kwargs)
    self.set_task(self.sample_tasks(1)[0])

    # @todo figure out what needs to be fixed here.
    EzPickle.__init__(self)
    self._goal_direction = goal_direction if goal_direction else 1.0
    pass

  def sample_tasks(self, num_tasks: int):
    """
    Sample a given number of goal velocities.

    Args:
      num_tasks (int): The number of tasks to sample from the current environment.

    Returns:
      (np.ndarray) an array of sampled values.
    """
    return np.random.choice((-1.0, 1.0), (num_tasks,))

  def set_task(self, task):
    """
    Args:
        task: task of the meta-learning environment
    """
    self._goal_direction = task

  def get_task(self):
    """
    Returns:
        task: task of the meta-learning environment
    """
    return self._goal_direction

  def step(self, action):
    """
    Given an action, take a step in the environment.

    Args:
      action (ActType): an action provided by the agent

    Returns:
      [ob, reward, done, dict] tuple containing observation, reward, whether an episode is done, and auxiliary
        diagnostic info.
    """
    x_pos_before = self.sim.data.qpos[0]
    self.do_simulation(action, self.frame_skip)
    x_pos_after = self.sim.data.qpos[0]
    ob = self._get_obs()

    reward_ctrl = - 0.5 * 0.1 * np.square(action).sum()
    reward_run = self._goal_direction * (x_pos_after - x_pos_before) / self.dt
    reward = reward_ctrl + reward_run

    done = False

    return ob, reward, done, dict(reward_run = reward_run, reward_ctrl = reward_ctrl)

  def _get_obs(self):
    """
    Returns the observation for the current step.

    Returns:
      (np.ndarray) with the observation.
    """
    return np.concatenate([
      self.sim.data.qpos.flat[1:],
      self.sim.data.qvel.flat,
    ])

  def reset_model(self):
    """
    Reset the current model of the environment and return the current observation for the environment.

    Returns:
      (np.ndarray) Current observation for the environment.
    """
    qpos = self.init_qpos + self.np_random.uniform(low = -.1, high = .1, size = self.model.nq)
    qvel = self.init_qvel + self.np_random.randn(self.model.nv) * .1
    self.set_state(qpos, qvel)

    return self._get_obs()

  def __str__(self):
    return 'HalfCheetahRandDirecEnv'

